import type { CardDefinition } from './types'

export const cards: CardDefinition[] = [
  {
    id: 'strike',
    name: '일격',
    type: 'attack',
    description: '적에게 피해 6을 줍니다.',
    cost: 2,
    source: 'starter',
    effect: { damage: 6 },
  },
  {
    id: 'guard',
    name: '방어',
    type: 'defense',
    description: '방어도 6을 얻습니다.',
    cost: 1,
    source: 'starter',
    effect: { block: 6 },
  },
  {
    id: 'heal',
    name: '치유',
    type: 'heal',
    description: '체력 5를 회복합니다.',
    cost: 1,
    source: 'starter',
    effect: { heal: 5 },
  },
  {
    id: 'poison_dart',
    name: '독침',
    type: 'debuff',
    description: '적에게 중독 3을 부여합니다.',
    cost: 1,
    source: 'starter',
    effect: { poison: 3 },
  },
  {
    id: 'focus',
    name: '집중',
    type: 'buff',
    description: '다음 공격 피해가 5 증가합니다.',
    cost: 1,
    source: 'starter',
    effect: { attackBonus: 5 },
  },
  {
    id: 'heavy_blow',
    name: '강타',
    type: 'attack',
    description: '적에게 피해 12를 주고 다음 턴에 카드를 1장 덜 뽑습니다.',
    cost: 2,
    source: 'reward',
    effect: { damage: 12, drawPenalty: 1 },
  },
  {
    id: 'double_hit',
    name: '연속 베기',
    type: 'attack',
    description: '적에게 피해 4를 두 번 줍니다.',
    cost: 2,
    source: 'reward',
    effect: { damage: 4, repeat: 2 },
  },
  {
    id: 'shield_bash',
    name: '방패 강타',
    type: 'attack',
    description: '현재 방어도만큼 적에게 피해를 줍니다.',
    cost: 2,
    source: 'reward',
    effect: { useBlockAsDamage: true },
  },
  {
    id: 'first_aid',
    name: '응급처치',
    type: 'heal',
    description: '체력 8을 회복합니다.',
    cost: 1,
    source: 'reward',
    effect: { heal: 8 },
  },
  {
    id: 'risky_attack',
    name: '무모한 일격',
    type: 'attack',
    description: '체력 3을 잃고 적에게 피해 15를 줍니다.',
    cost: 2,
    source: 'reward',
    effect: { damage: 15, selfDamage: 3 },
  },
  {
    id: 'iron_wall',
    name: '철벽',
    type: 'defense',
    description: '방어도 12를 얻습니다.',
    cost: 1,
    source: 'reward',
    effect: { block: 12 },
  },
  {
    id: 'venom_stack',
    name: '맹독 중첩',
    type: 'debuff',
    description: '적에게 중독 5를 부여합니다.',
    cost: 1,
    source: 'reward',
    effect: { poison: 5 },
  },
  {
    id: 'calm_mind',
    name: '평정심',
    type: 'buff',
    description: '체력 3을 회복하고 다음 공격 피해가 3 증가합니다.',
    cost: 1,
    source: 'reward',
    effect: { heal: 3, attackBonus: 3 },
  },
  {
    id: 'thorns',
    name: '가시 갑옷',
    type: 'defense',
    description: '방어도 8을 얻고 이번 턴에 받은 피해를 반사합니다.',
    cost: 1,
    source: 'reward',
    effect: { block: 8, reflectDamage: true },
  },
  {
    id: 'drain',
    name: '흡혈',
    type: 'attack',
    description: '적에게 피해 8을 주고 실제 피해량의 절반만큼 체력을 회복합니다.',
    cost: 2,
    source: 'reward',
    effect: { damage: 8, drainRatio: 0.5 },
  },
  {
    id: 'overload',
    name: '과부하',
    type: 'attack',
    description: '적에게 피해 20을 주지만 다음 2턴 동안 에너지가 1 줄어듭니다.',
    cost: 1,
    source: 'reward',
    effect: { damage: 20, energyPenalty: 1, energyPenaltyTurns: 2 },
  },
  {
    id: 'cleanse',
    name: '정화',
    type: 'buff',
    description: '내 중독을 모두 제거하고 다음 공격 피해가 4 증가합니다.',
    cost: 1,
    source: 'reward',
    effect: { cleanse: true, attackBonus: 4 },
  },
  {
    id: 'mimic',
    name: '흉내',
    type: 'buff',
    description: '적의 다음 행동을 복사해 먼저 사용합니다.',
    cost: 2,
    source: 'reward',
    effect: { mimicNext: true },
  },
]

export const starterCards = cards.filter((card) => card.source === 'starter')
export const rewardCards = cards.filter((card) => card.source === 'reward')
export const cardsById = Object.fromEntries(cards.map((card) => [card.id, card])) as Record<string, CardDefinition>
